version: '3.8'

services:
  
  mysql:
    image: mysql
    container_name: mysql-sql-demo
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bd_product
      MYSQL_USER: adama
      MYSQL_PASSWORD: passer123
    ports:
      - "33061:3306"
    networks:
      - spring-demo

  demo-terraform:
    container_name: demo-terraform
    image: adama93/demo-terraform:latest
    environment:
      - DATASOURCE_URL=jdbc:mysql://host.docker.internal:3306/bd_product
      - DATASOURCE_USERNAME=adama
      - DATASOURCE_PASSWORD=passer123
    ports:
      - 8087:8087
    # volumes:
    #   - bsn-api-storage:/app/uploads
    networks:
     - spring-demo
     - frontend
       
    depends_on:
      - mysql

  front-ui:
     container_name: front-ui
     image: adama93/front-ui:latest
     ports:
       - 8080:80
     networks:
       - spring-demo
       - frontend
     depends_on:
       - demo-terraform
networks:
  spring-demo:
  frontend:
   name: frontend
   external: true

volumes:
  mysql_data:
    driver: local
 