apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-terraform
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/SENCOINSN/demo-terraform.git
    targetRevision: HEAD
    path: kustome/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: demo-terraform-dev

  syncPolicy:
    syncOptions:
      - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true